### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'GetSelectedTarget'

### ISSUE THREAD

**Issue by l3d00m** [OpenImageDebugger/OpenImageDebugger#142]
**Environment (please complete the following information):**

- OID version (commit or tag) 99fe039fa44a249f0161c3187c8cb6c3a13eb9fa
- OS and Version Manjaro 23.1.0 Linux 6.6.1-1-MANJARO
- Which debugger [gdb or lldb] and version gdb
- Python version 3.11

**Describe the bug**

Similar to #26 

I'm running GDB with the Vscode C++ integration. I manually execute `-exec source /home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oid.py` in the vscode debug terminal (`-exec` flag is vscode specific, ignore it).

It returns 

```
Exception in thread Thread-2 (event_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 72, in event_loop
    self._check_frame_modification()
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 52, in _check_frame_modification
    process = self._get_process(self.get_lldb_backend())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 102, in _get_process
    return debugger.GetSelectedTarget().process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetSelectedTarget'
[OpenImageDebugger] Info: Could not activate hooks for any IDEs
```

![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/12055376/d9cc8830-3eff-4c33-a30b-b90a4b4c73f4)

Am I doing something wrong? I usually don't work with C++ or GDB, so it might be a rookie mistake.

**Comment by brunorosa-tomtom** [comment]
Hi @l3d00m, what are the gdb and lldb versions that you tried?

I guess there are two issues here:

1. first one is most likely due to a breaking change in lldb's python API: https://github.com/OpenImageDebugger/OpenImageDebugger/issues/38 
2. oid complaining lldb even using gdb

I don't know when I will have time to debug/fix them, but pull requests are more than welcome :)

**Comment by brunoalr** [comment]
Hi @l3d00m, what are the gdb and lldb versions that you tried?

I guess there are two issues here:

first one is most likely due to a breaking change in lldb's python API: https://github.com/OpenImageDebugger/OpenImageDebugger/issues/38
oid complaining lldb even using gdb
I don't know when I will have time to debug/fix them, but pull requests are more than welcome :)

**Comment by l3d00m** [comment]
Thanks for your reply. I'm currently busy, but I'll let you know on the weekend!

**Comment by l3d00m** [comment]
Running `GNU gdb (GDB) 13.2`. I have not tried `lldb` and never used it before.

Here's the complete output when running it directly inside GDB (without weird vscode stuff)

```
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/main...
(gdb) source /home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oid.py
Exception in thread Thread-1 (event_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 72, in event_loop
    self._check_frame_modification()
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 52, in _check_frame_modification
    process = self._get_process(self.get_lldb_backend())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/projects/OpenImageDebugger/bin/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 102, in _get_process
    return debugger.GetSelectedTarget().process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetSelectedTarget'
[OpenImageDebugger] Info: Could not activate hooks for any IDEs
(gdb) 
```

**Comment by dakhouya** [comment]
I retested on my side with the latest version (2ff16b9c5b2d55d4d83684eec62f11ae990608b2) and ubuntu22.04
I get this:
```
-exec source /workspaces/oid-devel/out/install/configure-debug/OpenImageDebugger/oid.py
[OpenImageDebugger] INFO: Could not activate hooks for any IDEs
```

On the other side @l3d00m using vscode you can source oid.py script in the launch.json so it will show up on breakpoint. See the section "Load oid.py script" bellow. 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                },
                {
                    "description": "Load oid.py script",
                    "text": "source ${workspaceFolder}/out/install/configure-debug/OpenImageDebugger/oid.py",
                    "ignoreFailures": true
                }
            ]
        }

    ]
}
```
