### ISSUE TITLE
Eigen matrices are not working, python crashes in gdb (solution is a one liner)

### ISSUE THREAD

**Issue by eallak** [OpenImageDebugger/OpenImageDebugger#157]
### Environment
- OID version (commit or tag): v1.9.20
- OS and Version: ubuntu 20.4
- Which debugger [gdb and/or lldb] and respective versions: gdb 9.2
- Python version: 3.8.10

### Describe the bug
The installation was very well documented and there were no problems.
I tried this tool out with a very small C++ file with small Eigen matrices. And although the variables are detected in the gui of OID correctly, they can not be plotted, because python crashed in the background.

### To Reproduce

1. debug a cpp file with eigen matrices with gdb
2. Select the variable in the gui

### Expected behavior

The matrix entries should be shown as an image.

### Actual behavior

No image is shown, only a traceback in gdb is shown.

### Error messages/stack traces

Please include error messages and/or stack traces in **plain text format**, preferrably using

```md
[OpenImageDebugger] Error: Could not plot variable
'gdb.Value' object has no attribute 'template_argument'
Traceback (most recent call last):
  File "/home/errr0/Downloads/vs_code/OpenImageDebugger/install/OpenImageDebugger/oidscripts/oidwindow.py", line 211, in __call__
    buffer_metadata = self._bridge.get_buffer_metadata(self._variable)
  File "/home/errr0/Downloads/vs_code/OpenImageDebugger/install/OpenImageDebugger/oidscripts/debuggers/gdbbridge.py", line 59, in get_buffer_metadata
    buffer_metadata = self._type_bridge.get_buffer_metadata(
  File "/home/errr0/Downloads/vs_code/OpenImageDebugger/install/OpenImageDebugger/oidscripts/typebridge.py", line 40, in get_buffer_metadata
    return module.get_buffer_metadata(symbol_name,
  File "/home/errr0/Downloads/vs_code/OpenImageDebugger/install/OpenImageDebugger/oidscripts/oidtypes/eigen3.py", line 93, in get_buffer_metadata
    eigen_stride = int(picked_obj.type.template_argument(2).template_argument(1)) # error: 'gdb.Value' object has no attribute 'template_argument'
AttributeError: 'gdb.Value' object has no attribute 'template_argument'
```

**Comment by eallak** [comment]
I already fixed it. Here is the solution:
In file /home/errr0/Downloads/vs_code/OpenImageDebugger/resources/oidscripts/oidtypes/eigen3.py on line 86 change the line as follows:
```python
#eigen_stride = int(picked_obj.type.template_argument(2).template_argument(1)) # error: 'gdb.Value' object has no attribute 'template_argument'
eigen_stride = int(picked_obj.type.template_argument(2))
```
I tested this with fixed size matrices, quadratic matrices, rectangular matrices and dynamic size matrices. It works for all.
Just wanted to let the community know :) maybe I should have made a pull request?
Please fix and close as you see fit.

**Comment by dakhouya** [comment]
I don't know that much eigen yet, but I think there might be an issue with the stride assignation regarding your remaining bug

```
eigen_stride = int(picked_obj.type.template_argument(2).template_argument(1))
row_stride = eigen_stride if eigen_stride > 0 else width
```

I replaced the row_stride assignation by

```
if transpose_buffer:
    width, height = height, width

row_stride = width
```
and it seem to fix your second issue. So the stride changed in function of the row or colomn major of eigen. I'm just not 100% sure on how the stride should be set with the eigen library. If there's some data alignment or something similar.

**Comment by eallak** [comment]
I tested your solution and it seems to fix it. I am not an eigen expert myself.

It seems like the variable eigen_stride was not even needed right?

Can be closed. Thanks!

**Comment by dakhouya** [comment]
@brunoalr if you approve that solution, I can open a PR if you want.
