### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GetSelectedTarget'

### ISSUE THREAD

**Issue by fushi219** [OpenImageDebugger/OpenImageDebugger#26]
Thanks for the great job！

My system environment is:

MacOS Big Sur 11.3.1 (20E241), python3.8 in X code. 

Following: https://github.com/OpenImageDebugger/OpenImageDebugger/wiki/Building-on-MacOS, I successfully compile the project. 

However, after import the oid.py script,  the lldb test program output as:

(lldb) Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/x/workspace/OpenImageDebugger/install/OpenImageDebugger/oidwindow.app/Contents/MacOS/oidscripts/debuggers/lldbbridge.py", line 69, in event_loop
    self._check_frame_modification()
  File "/Users/x/workspace/OpenImageDebugger/install/OpenImageDebugger/oidwindow.app/Contents/MacOS/oidscripts/debuggers/lldbbridge.py", line 49, in _check_frame_modification
    process = self._get_process(self.get_lldb_backend())
  File "/Users/x/workspace/OpenImageDebugger/install/OpenImageDebugger/oidwindow.app/Contents/MacOS/oidscripts/debuggers/lldbbridge.py", line 99, in _get_process
    return debugger.GetSelectedTarget().process
AttributeError: 'NoneType' object has no attribute 'GetSelectedTarget'

Any suggestions? Thanks a lot!

**Comment by fushi219** [comment]
I find that the error above ls caused by https://github.com/OpenImageDebugger/OpenImageDebugger/blob/main/resources/oidscripts/debuggers/lldbbridge.py#L43

after change it to 'return lldb.SBDebugger.Create()' the problem disappeared.

**Comment by brunoalr** [comment]
Hi @fushi219 ! thanks for the report and for the suggested fix.

Last time I checked there were some breaking API changes on lldb side, so newer versions might not work. Personally, I haven't had the time to work on OID lately, but my plan is to at least have a list of explicitly supported versions of the dependencies in the README.md file. I will create an issue for that and put it on the backlog.
