### ISSUE TITLE
Cannot view Eigen::MatrixXf when using CodeLLDB

### ISSUE THREAD

**Issue by JeremyShen3177** [OpenImageDebugger/OpenImageDebugger#93]
Thank you for your work, and it helps me a lot. 
When using CodeLLDB debug C++ project and I add cv::Mat items , it works well. But when I add Eigen::MatrixXf, it reports some error
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/72915191/7c6ba3f7-b642-4171-a019-d7cd45886900)
In addtion, my QT version is 5.7. When I build the project, I met an error and fix it, replace a function with “width()”.

**Comment by brunoalr** [comment]
Hi, @JeremyShen3177, thanks for the kind words.
I need a bit more info:
Which version of OID are you compiling? Which OS? Which debugger version? Which eigen version?
Could you upload a minimal example that reproduces the with instructions on how to build and reproduce the bug?
Also, please paste the error messages, since it's much easier to read plain text than looking at a screenshot :)

**Comment by brunoalr** [comment]
> In addtion, my QT version is 5.7. When I build the project, I met an error and fix it, replace a function with “width()”.

Thanks for finding this. Can you please open a pull request?

**Comment by JeremyShen3177** [comment]
> > In addtion, my QT version is 5.7. When I build the project, I met an error and fix it, replace a function with “width()”.
> 
> Thanks for finding this. Can you please open a pull request?

If pull the code, it may cause the project cant run on other QT version. Here is the git diff, hope it can works. It seems due to QT version update, and the API changes.
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/72915191/46bcc747-5a60-4744-afe2-b39fe83ca875)

**Comment by JeremyShen3177** [comment]
> Hi, @JeremyShen3177, thanks for the kind words. I need a bit more info: Which version of OID are you compiling? Which OS? Which debugger version? Which eigen version? Could you upload a minimal example that reproduces the with instructions on how to build and reproduce the bug? Also, please paste the error messages, since it's much easier to read plain text than looking at a screenshot :)

Thanks for your replay! 
Here is my environment:
Local commit : dbeeb50 2cfaa4b
UBUNTU: 20.04
LLDB: 10.0.0
gcc: 5.4
Eigen: 3.3.4
python: 3.8.2
Here is the error log:
Traceback (most recent call last):
  File "/home/syq/workspace/tools/OpenImageDebugger/OpenImageDebugger/oidscripts/oidwindow.py", line 211, in __call__
    buffer_metadata = self._bridge.get_buffer_metadata(self._variable)
  File "/home/syq/workspace/tools/OpenImageDebugger/OpenImageDebugger/oidscripts/debuggers/lldbbridge.py", line 130, in get_buffer_metadata
    buffer_metadata = self._type_bridge.get_buffer_metadata(
  File "/home/syq/workspace/tools/OpenImageDebugger/OpenImageDebugger/oidscripts/typebridge.py", line 40, in get_buffer_metadata
    return module.get_buffer_metadata(symbol_name,
  File "/home/syq/workspace/tools/OpenImageDebugger/OpenImageDebugger/oidscripts/oidtypes/eigen3.py", line 36, in get_buffer_metadata
    current_type = str(matrix_type_obj.template_argument(0))
AttributeError: 'str' object has no attribute 'template_argument'

**Comment by brunoalr** [comment]
Thanks for the extra info, what's missing now is:
* Could you upload a minimal example that reproduces the with instructions on how to build and reproduce the bug?

**Comment by brunoalr** [comment]
Hi, @JeremyShen3177, can you provide the missing info from my last comment?

**Comment by brunoalr** [comment]
Closing due to inactivity. Feel free to reopen.
